spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:agenthelper
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:oracle:thin:@database-4.cjedioeqnhkl.ap-northeast-2.rds.amazonaws.com/staging
    username: admin
    password: admin4321
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true

server:
  port: 8080

---

---

spring:
  config:
    activate:
      on-profile: pnuh_dev
  datasource:
    url: jdbc:oracle:thin:@database-4.cjedioeqnhkl.ap-northeast-2.rds.amazonaws.com/staging
    username: pnuh
    password: pnuh1234
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true

server:
  port: 9092

---

#jackson:
#  property-naming-strategy: SNAKE_CASE
spring:
  config:
    activate:
      on-profile: pnuh
  datasource:
    url: jdbc:oracle:thin:@200.100.1.116:1527/testdb
#    username: pnuhdba
#    password: pnuhdba
    username: mydata
    password: '*mydata128*'
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      schema: pnuhdba
  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        show_sql: false

server:
  port: 9092

